<?php

declare(strict_types=1);

namespace App\Actions\MaintenanceP;

use App\Contracts\HasDetail;
use App\Contracts\HasModule;
use App\Data\MaintenanceP\Sidebar;
use App\Data\MaintenanceP\Table;
use App\Data\Shared\Config;
use App\Data\Shared\Tabs;
use App\Models\MntPreventive;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Lorisleiva\Actions\Concerns\AsAction;
use Spatie\LaravelData\Data;

final class Index implements HasModule, HasDetail
{
    use AsAction;

    public function config(): Config
    {
        return new Config(
            title: 'Preventivos',
            subtitle: 'Machinery / Preventive Maintenance',
            icon: 'ri-calendar-check-line',
            newButtonLabel: 'Nueva Programación',
            showKpi: true,
            columns: [
                ['title' => 'ID', 'field' => 'id', 'width' => 60, 'sorter' => 'number', 'headerHozAlign' => 'center', 'headerFilter' => 'input'],
                ['title' => 'Start', 'field' => 'start', 'headerHozAlign' => 'center', 'headerFilter' => 'input'],
                ['title' => 'End', 'field' => 'end', 'headerHozAlign' => 'center', 'headerFilter' => 'input'],
                ['title' => 'Asset', 'field' => 'asset', 'headerHozAlign' => 'left', 'headerFilter' => 'input'],
                [
                    'title' => 'Status', 'field' => 'status', 'headerHozAlign' => 'center', 'hozAlign' => 'center',
                    'headerFilter' => 'list',
                    'headerFilterParams' => ['values' => ['Open' => 'Open', 'Started' => 'Started', 'Attended' => 'Attended', 'Closed' => 'Closed'], 'clearable' => true],
                ],
                ['title' => 'Days', 'field' => 'days', 'width' => 80, 'headerHozAlign' => 'center', 'formatter' => 'html'],
                ['title' => 'Activity', 'field' => 'activity', 'headerHozAlign' => 'left', 'headerFilter' => 'input'],
                ['title' => 'Frequency', 'field' => 'frequency', 'headerHozAlign' => 'left', 'headerFilter' => 'input'],
                ['title' => 'Started', 'field' => 'started', 'headerHozAlign' => 'center', 'headerFilter' => 'input'],
                ['title' => 'Attended', 'field' => 'attended', 'headerHozAlign' => 'center', 'headerFilter' => 'input'],
                ['title' => 'Closed', 'field' => 'closed', 'headerHozAlign' => 'center', 'headerFilter' => 'input'],
            ],
            // No create form — preventivos are generated by the system bot
            formFields: [],
            tabs: [
                new Tabs(key: 'detail', label: 'Detalle', icon: 'ri-information-line', route: 'maintenancep.detail', default: true),
                new Tabs(key: 'tasks', label: 'Bitácora',    icon: 'ri-list-check-2',      route: 'maintenancep.tasks'),
            ],
        );
    }

    public function asController(Request $request): View
    {
        return view('components.index', [
            'route'  => 'maintenancep',
            'config' => $this->config(),
        ]);
    }

    public function asData(Request $request): JsonResponse
    {
        $page   = max(1, (int) $request->integer('page', 1));
        $size   = max(1, (int) $request->integer('size', 50));
        $offset = ($page - 1) * $size;

        $query = MntPreventive::query()
            ->select([
                'mnt_preventive.id',
                'mnt_preventive.scheduled_start',
                'mnt_preventive.scheduled_end',
                'mnt_preventive.status',
                'mnt_preventive.started',
                'mnt_preventive.attended',
                'mnt_preventive.closed_at',
                DB::raw("COALESCE(NULLIF(mnt_preventive.activity, ''), forms.activity) as activity"),
                DB::raw('forms.frequency as frequency_value'),
                DB::raw("COALESCE(CONCAT(assets.hostname, ' | ', assets.serial), '') as asset_hostname"),
                DB::raw("DATE_PART('day', mnt_preventive.scheduled_end::timestamp - CURRENT_TIMESTAMP) as days_diff_count"),
            ])
            ->where('mnt_preventive.kind', 'Machinery')
            ->leftJoin('mnt_preventive_form as forms', 'mnt_preventive.preventive_id', '=', 'forms.id')
            ->leftJoin('assets', function ($join): void {
                $join->on('assets.id', '=', DB::raw('COALESCE(NULLIF(mnt_preventive.asset_id, 0), forms.asset_id)'));
            });

        // Filters
        $filters = $request->input('filters', $request->input('filter', []));
        if (is_array($filters)) {
            foreach ($filters as $f) {
                $field = (string) ($f['field'] ?? '');
                $value = $f['value'] ?? null;
                if ($value === null || $value === '') {
                    continue;
                }
                $v = (string) $value;
                match ($field) {
                    'activity'  => $query->where(DB::raw("COALESCE(NULLIF(mnt_preventive.activity, ''), forms.activity)"), 'ilike', "%{$v}%"),
                    'frequency' => $query->where('forms.frequency', 'ilike', "%{$v}%"),
                    'status'    => $query->where('mnt_preventive.status', $v),
                    'asset'     => $query->where(DB::raw("CONCAT(assets.hostname, ' | ', assets.serial)"), 'ilike', "%{$v}%"),
                    'id'        => $query->where('mnt_preventive.id', (int) $value),
                    default     => null,
                };
            }
        }

        // Sorters
        $sortRaw = $request->input('sorters', $request->input('sort', []));
        /** @var array{field?: string, dir?: string} $sort */
        $sort = is_array($sortRaw) && isset($sortRaw[0]) && is_array($sortRaw[0]) ? $sortRaw[0] : [];
        $sortField = match ($sort['field'] ?? '') {
            'status'   => 'status',
            'start'    => 'scheduled_start',
            'end'      => 'scheduled_end',
            'asset'    => 'assets.hostname',
            'activity' => 'mnt_preventive.activity',
            default    => 'mnt_preventive.id'
        };
        $sortDir = in_array(strtolower($sort['dir'] ?? ''), ['asc', 'desc'], true) ? $sort['dir'] : 'desc';

        if (($sort['field'] ?? '') === 'status') {
            $query->orderByRaw("CASE mnt_preventive.status
                WHEN 'Open'     THEN 1
                WHEN 'Started'  THEN 2
                WHEN 'Attended' THEN 3
                WHEN 'Closed'   THEN 4
                ELSE 5 END " . $sortDir);
        } else {
            $query->orderBy($sortField, $sortDir);
        }

        $total = $query->count();
        $rows  = $query->offset($offset)->limit($size)->get();

        $data = $rows->map(fn (MntPreventive $r): Table => Table::fromModel($r));

        return response()->json([
            'data'      => $data->values()->all(),
            'last_page' => (int) ceil($total / $size),
        ]);
    }

    public function sidebarData(int $id): Data
    {
        return Sidebar::fromModel(MntPreventive::with(['forms', 'asset'])->findOrFail($id));
    }
}
