<?php

declare(strict_types=1);

namespace App\Domain\MaintenanceP\Actions;

use App\Contracts\HasDetail;
use App\Contracts\HasModule;
use App\Domain\Maintenance\Models\MntPreventive;
use App\Domain\MaintenanceP\Data\Sidebar;
use App\Domain\MaintenanceP\Data\Table;
use App\Domain\Shared\Data\Config;
use App\Domain\Shared\Data\Tabs;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Lorisleiva\Actions\Concerns\AsAction;

final class Index implements HasDetail, HasModule
{
    use AsAction;

    public function config(): Config
    {
        return new Config(
            title: 'Preventivos',
            subtitle: 'Machinery / Preventive Maintenance',
            icon: 'ri-calendar-check-line',
            newButtonLabel: 'Nueva Programación',
            showKpi: true,
            columns: Table::columns(),
            // No create form — preventivos are generated by the system bot
            formFields: [],
            tabs: [
                new Tabs(key: 'detail', label: 'Detalle', icon: 'ri-information-line', route: 'maintenancep.detail', default: true),
                new Tabs(key: 'tasks', label: 'Bitácora', icon: 'ri-list-check-2', route: 'maintenancep.tasks'),
            ],
        );
    }

    public function asController(Request $request): View
    {
        return view('components.index', [
            'route' => 'maintenancep',
            'config' => $this->config(),
        ]);
    }

    public function asData(Request $request): JsonResponse
    {
        $page = max(1, (int) $request->integer('page', 1));
        $size = max(1, (int) $request->integer('size', 50));
        $offset = ($page - 1) * $size;

        $query = MntPreventive::query()
            ->select([
                'mnt_preventive.id',
                'mnt_preventive.scheduled_start',
                'mnt_preventive.scheduled_end',
                'mnt_preventive.status',
                'mnt_preventive.started',
                'mnt_preventive.attended',
                'mnt_preventive.closed_at',
                DB::raw("COALESCE(NULLIF(mnt_preventive.activity, ''), forms.activity) as activity"),
                DB::raw('forms.frequency as frequency_value'),
                DB::raw("COALESCE(CONCAT(assets.hostname, ' | ', assets.serial), '') as asset_hostname"),
                DB::raw("DATE_PART('day', mnt_preventive.scheduled_end::timestamp - CURRENT_TIMESTAMP) as days_diff_count"),
            ])
            ->where('mnt_preventive.kind', 'Machinery')
            ->leftJoin('mnt_preventive_form as forms', 'mnt_preventive.preventive_id', '=', 'forms.id')
            ->leftJoin('assets', function ($join): void {
                $join->on('assets.id', '=', DB::raw('COALESCE(NULLIF(mnt_preventive.asset_id, 0), forms.asset_id)'));
            });

        // Filters
        /** @var list<array{field: string, value: mixed}> $filters */
        $filters = (array) $request->input('filters', $request->input('filter', []));
        foreach ($filters as $f) {
            $field = (string) ($f['field'] ?? '');
            $value = $f['value'] ?? null;
            if (blank($value)) {
                continue;
            }
            if (! is_scalar($value)) {
                continue;
            }
            $v = (string) $value;
            match ($field) {
                'activity' => $query->where(DB::raw("COALESCE(NULLIF(mnt_preventive.activity, ''), forms.activity)"), 'ilike', "%{$v}%"),
                'frequency' => $query->where('forms.frequency', 'ilike', "%{$v}%"),
                'status' => $query->where('mnt_preventive.status', $v),
                'asset' => $query->where(DB::raw("CONCAT(assets.hostname, ' | ', assets.serial)"), 'ilike', "%{$v}%"),
                'id' => $query->where('mnt_preventive.id', (int) $value),
                default => null,
            };
        }

        // Sorters
        $sortRaw = $request->input('sorters', $request->input('sort', []));
        /** @var array{field?: string, dir?: string} $sort */
        $sort = is_array($sortRaw) && isset($sortRaw[0]) && is_array($sortRaw[0]) ? $sortRaw[0] : [];
        $sortField = match ($sort['field'] ?? '') {
            'status' => 'status',
            'start' => 'scheduled_start',
            'end' => 'scheduled_end',
            'asset' => 'assets.hostname',
            'activity' => 'mnt_preventive.activity',
            default => 'mnt_preventive.id'
        };
        $dir = strtolower((string) ($sort['dir'] ?? 'desc')) === 'asc' ? 'asc' : 'desc';

        if (($sort['field'] ?? '') === 'status') {
            if ($dir === 'asc') {
                $query->orderByRaw("CASE mnt_preventive.status
                    WHEN 'Open'     THEN 1
                    WHEN 'Started'  THEN 2
                    WHEN 'Attended' THEN 3
                    WHEN 'Closed'   THEN 4
                    ELSE 5 END asc");
            } else {
                $query->orderByRaw("CASE mnt_preventive.status
                    WHEN 'Open'     THEN 1
                    WHEN 'Started'  THEN 2
                    WHEN 'Attended' THEN 3
                    WHEN 'Closed'   THEN 4
                    ELSE 5 END desc");
            }
        } else {
            $query->orderBy($sortField, $dir);
        }

        $total = $query->count();
        $rows = $query->offset($offset)->limit($size)->get();

        $data = $rows->map(fn (MntPreventive $r): Table => Table::from($r));

        return response()->json([
            'data' => $data->values()->all(),
            'last_page' => (int) ceil($total / $size),
        ]);
    }

    public function sidebarData(int $id): Sidebar
    {
        return Sidebar::from(MntPreventive::with(['form', 'asset'])->findOrFail($id));
    }
}
